name: verovio
version: git
summary: Music notation engraving library for MEI
description: |
  Verovio is a fast, portable and lightweight 
  library for engraving Music Encoding Initiative (MEI) 
  digital scores into SVG images. Verovio also 
  contains on-the-fly converters to render 
  Plaine & Easie Code, Humdrum, Musedata, MusicXML, 
  EsAC, and ABC digital scores.

base: core18
confinement: strict

parts:
  verovio:
    plugin: autotools
    source-type: tar
    source: http://source.dosbox.com/dosboxsvn.tgz
    build-packages:
      - g++
      - make
