name: verovio
base: core18
version: git
summary: Music notation engraving library for MEI
description: |
  Verovio is a fast, portable and lightweight 
  library for engraving Music Encoding Initiative (MEI) 
  digital scores into SVG images. Verovio also 
  contains on-the-fly converters to render 
  Plaine & Easie Code, Humdrum, Musedata, MusicXML, 
  EsAC, and ABC digital scores.

grade: devel
confinement: strict

parts:
  verovio:
    plugin: cmake
    source: ../cmake/
    build-packages:
      - g++
      - make

